# SPDX-License-Identifier: MIT
---
- name: Install LINSTOR Gateway from package manager
  ansible.builtin.package:
    name: linstor-gateway
    state: "{{ gateway_install_package_state }}"
  register: _gateway_install_package
  ignore_errors: true
  notify: restart_linstor_gateway

# Currently only shipping amd64 builds for GitHub
- name: Install LINSTOR Gateway from GitHub
  ansible.builtin.get_url:
    url: 'https://github.com/LINBIT/linstor-gateway/releases/latest/download/linstor-gateway-linux-amd64'
    dest: '/usr/sbin/linstor-gateway'
    mode: '0755'
    force: "{{ gateway_install_package_state == 'latest' }}"
  when: _gateway_install_package is failed
  register: _gateway_installed_from_github
  until: _gateway_installed_from_github is succeeded
  retries: 3
  delay: 10
  notify: restart_linstor_gateway

- name: Configure LINSTOR Gateway # noqa: no-handler
  ansible.builtin.include_tasks: configure-gateway.yml
  when:
    (_gateway_install_package is changed) or
    (_gateway_installed_from_github is changed) or
    (gateway_install_force_reconfigure | bool)

- name: Verify the linstor-gateway binary is present and runnable
  ansible.builtin.command: linstor-gateway version
  changed_when: false
