# SPDX-License-Identifier: MIT
---
- name: Install LINSTOR Gateway from package manager
  ansible.builtin.package:
    name: linstor-gateway
    state: present
  failed_when: false
  notify: restart_linstor_gateway
  register: _gateway_install_package

- name: Install LINSTOR Gateway from GitHub
  ansible.builtin.get_url:
    url: "{{ linstor_gateway_github_binary }}"
    dest: '/usr/sbin/linstor-gateway'
    mode: '0755'
  register: _gateway_installed_from_github
  when: _gateway_install_package is failed
  notify: restart_linstor_gateway

- name: Configure LINSTOR Gateway # noqa: no-handler
  ansible.builtin.include_tasks: configure-gateway.yml
  when:
    (_gateway_install_package is changed) or
    (_gateway_installed_from_github is changed)
