# SPDX-License-Identifier: MIT
---
# defaults file for gateway_install

gateway_install_package_state: present

gateway_install_firewall_rules: true

gateway_install_firewall_ports:
  - { port: '8337', proto: tcp }

gateway_install_force_reconfigure: false
