# SPDX-License-Identifier: MIT
---
# defaults file for gateway_install

gateway_install_package_state: present

gateway_install_from_github: false

gateway_install_firewall_rules: true

# firewalld zone for the ports below. Empty uses the default zone
gateway_install_firewalld_zone: ""

gateway_install_firewall_ports:
  - { port: '8337', proto: tcp, zone: "{{ gateway_install_firewalld_zone }}" }

gateway_install_force_reconfigure: false

# Delegation target for LINSTOR API tasks
# Override if Ansible control node cannot reach LINSTOR controller API endpoint
linstor_api_delegate: localhost
