# SPDX-License-Identifier: MIT
---
- name: Open UFW ports for the LINSTOR controller proxy
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ _ha_controller_proxy_firewall_ports }}"
