# SPDX-License-Identifier: MIT
---
- name: Open firewalld ports for the LINSTOR controller proxy
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    zone: "{{ item.zone | default(omit, true) }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ _ha_controller_proxy_firewall_ports }}"
