# SPDX-License-Identifier: MIT
namespace: linbit
name: linstor
version: 0.9.5
readme: README.md
authors:
- Ryan Ronnander <rronnander@linbit.com>
- Matt Kereczman <matt@linbit.com>
- Michael Troutman <michael@linbit.com>
- Devin Vance <devin@linbit.com>
description: Ansible roles and modules for deploying and managing LINSTOR storage clusters, including controller, satellite, client, and LINSTOR Gateway components
license:
- MIT
tags:
- linbit
- linstor
- storage
- gateway
- nfs
- iscsi
- nvmeof
- ha
- drbd
dependencies:
  ansible.posix: '*'
  ansible.utils: '>=2.0.0'
  community.general: '>=10.4.0'
  # linbit.common: '*'       # uncomment when published to Ansible Galaxy
  # linbit.drbd: '*'         # uncomment when published to Ansible Galaxy
  # linbit.drbd_reactor: '*' # uncomment when published to Ansible Galaxy
repository: https://gitlab.at.linbit.com/ansible-collections/linbit.linstor
documentation: https://linbit.com/user-guides-and-product-documentation/
homepage: https://linbit.com
issues: https://gitlab.at.linbit.com/ansible-collections/linbit.linstor/-/issues
