# SPDX-License-Identifier: MIT
namespace: linbit
name: linstor
version: 0.9.0
readme: README.md
authors:
- LINBIT <info@linbit.com>
description: Full LINSTOR stack: client, controller, satellite, and LINSTOR Gateway for NFS and iSCSI HA
license:
- MIT
tags:
- linbit
- linstor
- storage
- gateway
- nfs
- iscsi
- ha
- drbd
dependencies: {}
repository: https://gitlab.at.linbit.com/ansible-collections/linbit.linstor
documentation: https://linbit.com/linbit-software-download/
homepage: https://linbit.com
issues: https://gitlab.at.linbit.com/ansible-collections/linbit.linstor/-/issues
