# SPDX-License-Identifier: MIT
---
- name: Add openSUSE filesystems repository for ZFS
  community.general.zypper_repository:
    repo: "https://download.opensuse.org/repositories/filesystems/{{ ansible_facts['distribution_version'] }}/filesystems.repo"
    auto_import_keys: true
    state: present

- name: Install ZFS packages (Zypper)
  community.general.zypper:
    name: zfs
    state: present
  register: _satellite_install_zfs_zypper
  until: _satellite_install_zfs_zypper is succeeded
  retries: 3
  delay: 10

- name: Check if system uses UEFI
  ansible.builtin.stat:
    path: /sys/firmware/efi
  register: _satellite_install_efi_check

- name: Install ZFS UEFI certificate for Secure Boot
  community.general.zypper:
    name: zfs-ueficert
    state: present
  when: _satellite_install_efi_check.stat.exists
  register: _satellite_install_zfs_ueficert
  until: _satellite_install_zfs_ueficert is succeeded
  retries: 3
  delay: 10

- name: Reboot to enroll ZFS signing key in MOK
  ansible.builtin.reboot:
  when:
    - _satellite_install_efi_check.stat.exists
    - _satellite_install_zfs_ueficert is changed
