# SPDX-License-Identifier: MIT
---
- name: Install EPEL on Oracle Linux (DNF)
  ansible.builtin.dnf:
    name: "oracle-epel-release-el{{ ansible_facts['distribution_major_version'] }}"
    state: present
  when: ansible_facts['distribution'] | lower == 'oraclelinux'
  register: _satellite_install_epel_oracle
  until: _satellite_install_epel_oracle is succeeded
  retries: 3
  delay: 10

- name: Install EPEL on other RPM distros (DNF)
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: ansible_facts['distribution'] | lower != 'oraclelinux'
  register: _satellite_install_epel
  until: _satellite_install_epel is succeeded
  retries: 3
  delay: 10

- name: Install ZFS repository
  ansible.builtin.dnf:
    name: "https://zfsonlinux.org/epel/zfs-release-3-0{{ ansible_facts['distribution_version'] | regex_replace('^(\\d+).*', '.el\\1') }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  register: _satellite_install_zfs_repo
  until: _satellite_install_zfs_repo is succeeded
  retries: 3
  delay: 10

- name: Disable ZFS DKMS repository
  ansible.builtin.command:
    cmd: dnf config-manager --disable zfs
  changed_when: false

- name: Enable ZFS kmod repository
  ansible.builtin.command:
    cmd: dnf config-manager --enable zfs-kmod
  changed_when: false

- name: Install ZFS packages (DNF)
  ansible.builtin.dnf:
    name: zfs
    state: present
  register: _satellite_install_zfs_dnf
  until: _satellite_install_zfs_dnf is succeeded
  retries: 3
  delay: 10
