# SPDX-License-Identifier: MIT
---
- name: Lock LINSTOR satellite package versions (APT)
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - linstor-satellite
    - linstor-common
