# SPDX-License-Identifier: MIT
---
# tasks file for linstor-satellite
- name: Load OS-specific variables for satellite_install
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Install LINSTOR satellite packages
  ansible.builtin.package:
    name: "{{ linstor_satellite_packages + linstor_zfs_packages }}"
    state: present
  notify: sat_package_update

- name: Open firewall ports for LINSTOR satellite
  ansible.builtin.include_tasks: firewall.yml
  when: satellite_install_firewall_rules | bool

# https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-linstor-storage-pools-creating
- name: Check for /etc/lvm/lvm.conf
  ansible.builtin.stat:
    path: /etc/lvm/lvm.conf
  register: _lvm_check

- name: Modify lvm.conf global filter for DRBD devices
  ansible.builtin.lineinfile:
    path: /etc/lvm/lvm.conf
    line: 'global_filter = [ "r|^/dev/drbd|", "r|^/dev/mapper/[lL]instor|" ]'
    regexp: 'global_filter'
  when: _lvm_check.stat.exists

- name: Flush handlers for satellite_install
  ansible.builtin.meta: flush_handlers
