# SPDX-License-Identifier: MIT
---
# tasks file for linstor-satellite
- name: Check if linstor-satellite is already installed
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/linstor-satellite.service
  register: _satellite_install_check

- name: Install and configure LINSTOR satellite
  when:
    - "not _satellite_install_check.stat.exists
      or satellite_install_package_state != 'present'"
  block:
    - name: Install ZFS utilities
      ansible.builtin.include_tasks: install-zfs.yml
      when: satellite_install_zfs | bool

    - name: Install satellite prerequisites
      ansible.builtin.package:
        name: "{{ _satellite_install_prereqs }}"
        state: present

    - name: Install LINSTOR satellite
      ansible.builtin.package:
        name: linstor-satellite
        state: "{{ satellite_install_package_state }}"
      register: _satellite_install_packages
      notify: sat_package_update

    - name: Configure LINSTOR satellite
      ansible.builtin.include_tasks: configure-satellite.yml
      when: _satellite_install_packages is changed  # noqa: no-handler
