# SPDX-License-Identifier: MIT
---
# tasks file for linstor-satellite
- name: Load OS-specific variables for satellite_install
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Check for LINSTOR satellite updates
  ansible.builtin.package:
    name: "{{ satellite_install_packages + satellite_install_zfs_packages }}"
    state: "{{ satellite_install_package_state }}"
  register: _satellite_install_packages
  notify: sat_package_update

- name: Configure LINSTOR satellite
  ansible.builtin.include_tasks: configure-satellite.yml
  when: _satellite_install_packages is changed  # noqa: no-handler
