# SPDX-License-Identifier: MIT
---
# Node hostname for LINSTOR registration.
# Forces short hostnames on Proxmox VE (detected via kernel version), unaltered otherwise.
linstor_hostname: >-
  {{
    inventory_hostname_short
    if 'pve' in ansible_facts['kernel']
    else inventory_hostname
  }}

# Network communication type for node registration (Plain or SSL)
cluster_membership_com_type: Plain

# Network port for node registration
cluster_membership_port: 3366
