# SPDX-License-Identifier: MIT
---
# handlers file for ssl

- name: Restart LINSTOR controller for SSL
  ansible.builtin.systemd_service:
    name: linstor-controller.service
    daemon_reload: true
    state: restarted
  listen: restart_linstor_controller_ssl

- name: Wait for LINSTOR controller after SSL restart
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ ssl_init_https_port if ssl_init_https | bool else 3370 }}"
    delay: 5
    timeout: 30
  listen: restart_linstor_controller_ssl

- name: Restart LINSTOR satellite for SSL
  ansible.builtin.systemd_service:
    name: linstor-satellite.service
    daemon_reload: true
    state: restarted
  listen: restart_linstor_satellite_ssl

- name: Wait for LINSTOR satellite after SSL restart
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ ssl_init_satellite_port if ssl_init_satellite | bool else 3366 }}"
    delay: 5
    timeout: 20
  listen: restart_linstor_satellite_ssl
