# SPDX-License-Identifier: MIT
---
# defaults file for linstor_gateway_install_client

# Only amd64 linstor-gateway builds exist currently
linstor_gw_github_release: 'https://github.com/LINBIT/linstor-gateway/releases/latest/download/linstor-gateway-linux-amd64'
