# SPDX-License-Identifier: MIT
---
# vars file for gateway_satellite - Debian family (Debian and Ubuntu)
gateway_satellite_supplemental_packages:
  - iptables # for portblock
  - nfs-kernel-server
  - nfs-common
  - psmisc
  - rpcbind
  - targetcli-fb
  - xfsprogs
