# SPDX-License-Identifier: MIT
---
# vars file for gateway_satellite
gateway_satellite_supplemental_packages:
  - iptables # for portblock
  - nfs-kernel-server
  - nfs-common
  - psmisc # Missing from Debian? Might not be included in minimal installs
  - rpcbind
  - targetcli-fb
  - xfsprogs  # for debian
