# SPDX-License-Identifier: MIT
---
# vars file for gateway_satellite
gateway_satellite_supplemental_packages:
  - iptables # for portblock
  - "linux-modules-extra-{{ ansible_kernel }}" # nvmet-tcp for NVMe-oF targets
  - nfs-kernel-server
  - nfs-common
  - psmisc
  - rpcbind
  - targetcli-fb
  - xfsprogs
