# SPDX-License-Identifier: MIT
---
- name: Ensure root linstor config directory exists on the controller
  ansible.builtin.file:
    path: /root/.config/linstor
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Render root linstor-client.conf on the controller
  ansible.builtin.template:
    src: linstor-client.j2
    dest: /root/.config/linstor/linstor-client.conf
    owner: root
    group: root
    mode: '0600'
