# SPDX-License-Identifier: MIT
---
- name: Check if linstor-client is already installed
  ansible.builtin.stat:
    path: "{{ _client_install_linstor_path }}"
  register: _client_install_check

- name: Install linstor-client
  ansible.builtin.package:
    name: linstor-client
    state: "{{ client_install_package_state }}"
  when:
    - not _client_install_check.stat.exists
      or client_install_package_state != 'present'
  register: _client_install_package
  until: _client_install_package is succeeded
  retries: 3
  delay: 10

- name: Configure linstor-client # noqa: no-handler
  ansible.builtin.include_tasks: configure-client.yml
  when:
    (_client_install_package is changed) or
    (client_install_force_reconfigure | bool)
