# SPDX-License-Identifier: MIT
---
- name: Install linstor-client
  ansible.builtin.package:
    name: linstor-client
    state: present
  register: _client_install_package

- name: Configure linstor-client
  ansible.builtin.include_tasks: configure-client.yml
  when: _client_install_package is changed # noqa: no-handler
