# SPDX-License-Identifier: MIT
---
- name: Load OS-specific variables for LINSTOR Gateway satellite
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | int }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Install DRBD Reactor
  ansible.builtin.include_role:
    name: linbit.drbd_reactor.reactor_install
  when: "'drbd-reactor.service' not in ansible_facts.services"

- name: Install HA dependencies
  when: inventory_hostname not in groups.get('linstor_diskless_satellites', [])
  block:
    - name: Check for portblock resource agent
      ansible.builtin.stat:
        path: "{{ linstor_gateway_portblock_ra_dest }}"
      register: portblock_ra_check

    - name: Fix portblock resource agent - remove immutable flag
      ansible.builtin.file:
        path: "{{ linstor_gateway_portblock_ra_dest }}"
        attributes: '-i'
      when:
        - linstor_gateway_portblock_fix | bool
        - portblock_ra_check.stat.exists

    - name: Install LINSTOR Gateway supplemental packages
      ansible.builtin.package:
        name: "{{ linstor_gateway_supplemental_packages + linstor_gateway_ra_packages }}"
        state: present
      failed_when: false # for now, clear up packaging assumptions later
      notify: disable_and_stop_nfs

    - name: Install SCST
      ansible.builtin.include_tasks: scst.yml
      when: linstor_gateway_scst | bool

    - name: Open firewalld ports for LINSTOR Gateway satellite services
      ansible.posix.firewalld:
        service: "{{ item.name }}"
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - "{{ linstor_gateway_firewalld_services }}"
      when:
        - ansible_facts.services['firewalld.service'] is defined
        - ansible_facts.services['firewalld.service'].state == 'running'

    - name: Fix portblock resource agent - overwrite and set immutable flag
      ansible.builtin.get_url:
        url: "{{ linstor_gateway_portblock_ra_url }}"
        dest: "{{ linstor_gateway_portblock_ra_dest }}"
        mode: '755'
        attributes: '+i'
      when:
        - linstor_gateway_portblock_fix | bool
        - portblock_ra_check.stat.exists

- name: Patch linstor_satellite.toml for DRBD Reactor
  ansible.builtin.blockinfile:
    path: /etc/linstor/linstor_satellite.toml
    marker: "# {mark} ANSIBLE MANAGED FILE"
    block: "{{ lookup('template', 'linstor_satellite.j2') }}"
    create: true
    mode: '644'
    state: present
  notify: restart_linstor_satellite
  when:
    - "'linstor_satellites' in groups"
    - inventory_hostname in groups['linstor_satellites']

- name: Flush handlers for linstor_gateway_satellite
  ansible.builtin.meta: flush_handlers
