# SPDX-License-Identifier: MIT
---
- name: Open firewalld ports for LINSTOR Gateway satellite services
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    zone: "{{ item.zone | default(omit, true) }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ gateway_satellite_firewall_ports }}"
