# SPDX-License-Identifier: MIT
---
# Install SCST iSCSI target from source.
# Triggered when linstor_gateway_scst=true.

- name: Check if SCST kernel module is already loaded
  ansible.builtin.stat:
    path: /sys/module/scst
  register: scst_module

- name: Build and install SCST from source
  when: not scst_module.stat.exists
  block:
    - name: Install git
      ansible.builtin.package:
        name: git
        state: present

    - name: Checkout SCST repo
      ansible.builtin.git: # noqa: latest[git]
        repo: 'https://github.com/SCST-project/scst.git'
        version: "{{ linstor_gateway_scst_version }}"
        dest: /tmp/scst

    - name: Build and install SCST (RHEL)
      when: ansible_facts['os_family'] | lower == 'redhat'
      block:
        - name: Install EPEL repo
          ansible.builtin.package:
            name: epel-release
            state: present

        - name: Install SCST build prerequisites (RHEL)
          ansible.builtin.package:
            name:
              - '@Development tools'
              - kernel-devel
              - perl
              - perl-Data-Dumper
              - perl-ExtUtils-MakeMaker
              - rpm-build
              - dkms
            state: present

        - name: Compile SCST RPMs
          ansible.builtin.shell: |
            cd /tmp/scst
            make rpm-dkms
            rm -f /usr/src/packages/RPMS/x86_64/*debug*
          args:
            creates: /usr/src/packages/RPMS/x86_64/scst-dkms-*.rpm

        - name: Install SCST RPMs
          ansible.builtin.shell: |
            dnf install -y /usr/src/packages/RPMS/x86_64/scst*.rpm
          register: scst_rpm_install
          changed_when: "'Nothing to do' not in scst_rpm_install.stdout"

    - name: Build and install SCST (Debian)
      when: ansible_facts['os_family'] | lower == 'debian'
      block:
        - name: Install SCST build prerequisites (Debian)
          ansible.builtin.package:
            name:
              - build-essential
              - debhelper
              - devscripts
              - gcc
              - make
              - lintian
              - quilt
            state: present

        # SCST uses DKMS, so install headers for all installed kernels.
        - name: Install PVE kernel headers (Proxmox VE)
          ansible.builtin.package:
            name: proxmox-default-headers
            state: present
          when: _pve_check | bool

        - name: Install Debian kernel headers
          ansible.builtin.package:
            name: "linux-headers-{{ _debian_arch }}"
            state: present
          when: "'pve' not in ansible_facts['kernel']"

        - name: Compile SCST .deb packages
          ansible.builtin.shell: |
            cd /tmp/scst
            make 2release
            make dpkg 1>/dev/null 2>/dev/null
          failed_when: false
          changed_when: true

        - name: Install SCST .deb packages
          ansible.builtin.shell: |
            dpkg -i /tmp/scst/dpkg/iscsi-scst_*.deb
            dpkg -i /tmp/scst/dpkg/scstadmin_*.deb
            dpkg -i /tmp/scst/dpkg/scst-dev_*.deb
            dpkg -i /tmp/scst/dpkg/scst-dkms_*.deb
          register: scst_deb_install
          changed_when: "'already installed' not in scst_deb_install.stderr"

    - name: Remove SCST build directory
      ansible.builtin.file:
        path: /tmp/scst
        state: absent

# https://github.com/LINBIT/linstor-gateway/issues/24#issuecomment-1800271696
- name: Load SCST kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    persistent: present
    state: present
  loop:
    - scst
    - iscsi-scst
    - scst_vdisk

- name: Create iscsi-scst service unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/iscsi-scst.service
    mode: '0644'
    content: |
      [Unit]
      Description=iSCSI SCST Target Daemon
      Documentation=man:iscsi-scstd(8)
      After=network.target
      Before=scst.service
      Conflicts=shutdown.target

      [Service]
      EnvironmentFile=-/etc/sysconfig/scst
      PIDFile=/run/iscsi-scstd.pid
      ExecStartPre=/sbin/modprobe iscsi-scst
      ExecStart=/sbin/iscsi-scstd $ISCSID_OPTIONS

      [Install]
      WantedBy=multi-user.target

- name: Start and enable iscsi-scst service
  ansible.builtin.systemd_service:
    name: iscsi-scst.service
    daemon_reload: true
    state: started
    enabled: true
