# SPDX-License-Identifier: MIT
---
- name: Load OS-specific variables for LINSTOR Gateway satellite
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | int }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Install DRBD Reactor
  ansible.builtin.include_role:
    name: linbit.drbd_reactor.reactor_install
  vars:
    reactor_install_resource_agents_github: true

- name: Install HA dependencies
  when: inventory_hostname not in groups.get('linstor_diskless_satellites', [])
  block:
    - name: Install LINSTOR Gateway supplemental packages
      ansible.builtin.package:
        name: "{{ linstor_gateway_supplemental_packages }}"
        state: present
      failed_when: false # for now, clear up packaging assumptions later
      notify: disable_and_stop_nfs

    - name: Install SCST
      ansible.builtin.include_tasks: install-scst.yml
      when: linstor_gateway_scst | bool

    - name: Open firewall ports for LINSTOR Gateway satellite services
      ansible.builtin.include_tasks: open-firewall.yml
      when: linstor_gateway_firewall_rules | bool

- name: Patch linstor_satellite.toml for DRBD Reactor
  ansible.builtin.blockinfile:
    path: /etc/linstor/linstor_satellite.toml
    marker: "# {mark} ANSIBLE MANAGED FILE"
    block: "{{ lookup('template', 'linstor_satellite.j2') }}"
    create: true
    mode: '0644'
    state: present
  notify: restart_linstor_satellite
  when:
    - "'linstor_satellites' in groups"
    - inventory_hostname in groups['linstor_satellites']

- name: Set GatewaySatellite aux property on satellite nodes
  linbit.linstor.node:
    name: "{{ linstor_hostname }}"
    aux_properties:
      GatewaySatellite: "True"
  delegate_to: "{{ groups['linstor_controllers'][0] }}"
  when: inventory_hostname in groups['linstor_satellites']

- name: Flush handlers for gateway_satellite
  ansible.builtin.meta: flush_handlers
