# SPDX-License-Identifier: MIT
---
# Shared defaults for all gateway protocols
ha_gateway_storage_pool: ""
ha_gateway_place_count: 2
ha_gateway_tickle_dir_size: 64M
ha_gateway_fstype: ext4

# Force 4K blocksize for cross-node 4Kn sector compatibility
ha_gateway_filesystem_blocksize: 4096

ha_gateway_drbd_options:
  auto-promote: 'no'
  quorum: majority
  on-suspended-primary-outdated: 'force-secondary'
  on-no-quorum: 'io-error'

# iSCSI-specific defaults
ha_gateway_iscsi_port: 3260
ha_gateway_iscsi_iqn_base: iqn.2026-06.com.linbit

# NFS-specific defaults
ha_gateway_nfs_port: 2049
ha_gateway_nfsv4_only: false # currently broken due to upstream nfsserver RA
ha_gateway_nfs_allowed_ips:
  - "0.0.0.0/0.0.0.0"
ha_gateway_nfs_options: rw,all_squash,anonuid=0,anongid=0

# NVMe-oF-specific defaults
ha_gateway_nvmeof_port: 4420
ha_gateway_nvmeof_nqn_base: "nqn.2026-06.io.linbit:nvme"

# Delegation target for LINSTOR API tasks
# Override if Ansible control node cannot reach LINSTOR controller API endpoint
linstor_api_delegate: localhost
