# SPDX-License-Identifier: MIT
---
storage_pool_defaults:
  type: lvmthin
  vg_thinpool: thinpool
  file_path: '/var/lib/linstor-filethin/'
  thinpool_size: '95%VG'
  pv_create_options: ""
  lv_create_options: ""
  zfs_create_options: ""
  zpool_vdev_type: stripe
  zpool_properties: {}
  vdevs: []
  wipefs_force: false

# Delegation target for LINSTOR API tasks
# Override if Ansible control node cannot reach LINSTOR controller API endpoint
linstor_api_delegate: localhost
