# SPDX-License-Identifier: MIT
---
# defaults file for linstor_satellite
# client_install role handles LINSTOR client packages and configuration
satellite_install_package_state: present

# Enable ZFS storage pool support for Debian OS family
satellite_install_zfs: true

# Enable ZFS storage pool support for RedHat/SUSE OS family
satellite_install_zfs_all_distros: false

satellite_install_packages:
  - cryptsetup    # pre-req for luks
  - socat
  - lvm2 # For Debian systems
  - thin-send-recv
  - zstd
  - linstor-satellite

satellite_install_firewall_rules: true

satellite_install_firewall_ports:
  - { port: '3366-3367', proto: tcp }
  - { port: '7000-8000', proto: tcp }
