# SPDX-License-Identifier: MIT
---
# defaults file for linstor_satellite
# client_install role handles client packages
satellite_install_package_state: latest

satellite_install_packages:
  - cryptsetup    # pre-req for luks
  - socat
  - lvm2 # For Debian systems
  - thin-send-recv
  - zstd
  - linstor-satellite

# placeholder for Ubuntu
satellite_install_zfs_packages: []

satellite_install_firewall_rules: true

satellite_install_firewall_ports:
  - { port: '3366-3367', proto: tcp }
  - { port: '7000-8000', proto: tcp }
