# SPDX-License-Identifier: MIT-0
---
# vars file for linstor_gateway_install
linstor_gateway_supplemental_packages:
  # - drbd-reactor # installed by role!
  - iptables # for portblock
  - nvmetcli
  - nfs-utils
  - psmisc # Missing from Debian? Might not be included in minimal installs
  - resource-agents
  - rpcbind
  - targetcli
