# SPDX-License-Identifier: MIT
---
# defaults file for client_install
client_install_package_state: present
linstor_controller_addresses: "{{ query('linbit.linstor.group_addresses', 'linstor_controllers') }}"

linstor_client_https: false
linstor_client_cafile: ""
linstor_client_certfile: ""
linstor_client_keyfile: ""
linstor_client_auth_token: ""

client_install_force_reconfigure: false
