# SPDX-License-Identifier: MIT
galaxy_info:
  author: LINBIT
  description: Install and configure the LINSTOR controller
  company: LINBIT

  license: MIT

  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - jammy
        - noble
        - resolute
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
    - name: opensuse
      versions:
        - "15.6"
    - name: SLES
      versions:
        - 15SP6

  min_ansible_version: 2.1

  galaxy_tags:
    - linbit
    - linstor
    - storage
    - controller

dependencies:
  - role: linbit.linstor.linstor_client
