# SPDX-License-Identifier: MIT
---
ha_database_pool: ""
ha_database_rg: linstor-db-grp
ha_database_res: linstor_db
ha_database_res_size: 200M

ha_database_filesystem: ext4
# Force 4K blocksize for cross-node 4Kn sector compatibility
ha_database_filesystem_blocksize: 4096

ha_database_max_controllers: 3

ha_database_allow_2_replica: false

ha_database_vip: ""

ha_database_haproxy: false

ha_database_drbd_options:
  resource:
    auto-promote: "no"
    quorum: majority
    on-no-quorum: io-error
    on-no-data-accessible: io-error
    on-suspended-primary-outdated: force-secondary

# Delegation target for LINSTOR API tasks
# Override if Ansible control node cannot reach LINSTOR controller API endpoint
linstor_api_delegate: localhost
