# SPDX-License-Identifier: MIT
---
- name: Set pool type
  ansible.builtin.set_fact:
    _type: "{{ _pool.type | default(storage_pool_defaults.type) }}"

- name: Compute driver pool value
  ansible.builtin.set_fact:
    _driver_pool: >-
      {%- if _type in ['file', 'filethin'] -%}
        {{ _pool.file_path | default(storage_pool_defaults.file_path) }}
      {%- elif _type == 'lvmthin' -%}
        {{ _pool.vg }}/{{ _pool.vg_thinpool | default(storage_pool_defaults.vg_thinpool) }}
      {%- elif _type in ['zfs', 'zfsthin'] -%}
        {{ _pool.zpool }}
      {%- else -%}
        {{ _pool.vg }}
      {%- endif -%}

- name: Check if storage pool exists
  linbit.linstor.storage_pool:
    name: "{{ _pool.name }}"
    node: "{{ linstor_hostname }}"
    driver: "{{ _type }}"
    driver_pool: "{{ _driver_pool | trim }}"
  check_mode: true
  register: _storage_pool_check

- name: Create storage pool
  ansible.builtin.include_tasks: create-pool.yml
  when: _storage_pool_check is changed
