# SPDX-License-Identifier: MIT
---
- name: Configure LINBIT public repo
  ansible.builtin.include_role:
    name: linbit.common.public_repo
    apply:
      tags:
        - linstor
        - linstor_registration
  when: cluster_init_public_repo | bool
  tags:
    - linstor
    - linstor_registration

- name: Configure LINBIT customer repo
  ansible.builtin.include_role:
    name: linbit.common.customer_repo
    apply:
      tags:
        - linstor
        - linstor_registration
  when:
    - cluster_init_customer_repo | bool
    - not (cluster_init_public_repo | bool)
  tags:
    - linstor
    - linstor_registration

- name: Install LINSTOR satellite
  ansible.builtin.include_role:
    name: linbit.linstor.satellite_install
    apply:
      tags:
        - linstor
        - linstor_installation
  when: inventory_hostname in groups['linstor_satellites']
  tags:
    - linstor
    - linstor_installation

- name: Install LINSTOR controller
  ansible.builtin.include_role:
    name: linbit.linstor.controller_install
    apply:
      tags:
        - linstor
        - linstor_installation
  when: inventory_hostname in groups['linstor_controllers']
  tags:
    - linstor
    - linstor_installation

- name: Register LINSTOR cluster membership
  ansible.builtin.include_role:
    name: linbit.linstor.cluster_membership
    apply:
      tags:
        - linstor
        - linstor_cluster_membership
  tags:
    - linstor
    - linstor_cluster_membership

- name: Install LINSTOR Gateway
  ansible.builtin.include_role:
    name: linbit.linstor.linstor_gateway_install
    apply:
      tags:
        - linstor
        - linstor_installation
        - linstor_gateway
  when: cluster_init_linstor_gateway | bool
  tags:
    - linstor
    - linstor_installation
    - linstor_gateway

- name: Create LINSTOR storage pools
  ansible.builtin.include_role:
    name: linbit.linstor.storage_pool
    apply:
      tags:
        - linstor
        - linstor_storage_pool
  when:
    - cluster_init_deploy_storage | bool
    - inventory_hostname in groups['linstor_diskful_satellites']
  tags:
    - linstor
    - linstor_storage_pool

# Requires a configured storage pool
- name: Convert LINSTOR database to HA
  ansible.builtin.include_role:
    name: linbit.linstor.ha_database
    apply:
      tags:
        - linstor
        - linstor_ha_database
  when:
    - cluster_init_deploy_storage | bool
    - cluster_init_ha_database | bool
  tags:
    - linstor
    - linstor_ha_database
