# SPDX-License-Identifier: MIT
---
- name: Install LINSTOR satellite
  ansible.builtin.import_role:
    name: linbit.linstor.satellite_install
  when: inventory_hostname in groups['linstor_satellites']

- name: Install LINSTOR controller
  ansible.builtin.import_role:
    name: linbit.linstor.controller_install
  when: inventory_hostname in groups['linstor_controllers']

- name: Register LINSTOR cluster membership
  ansible.builtin.import_role:
    name: linbit.linstor.cluster_membership
