# SPDX-License-Identifier: MIT
---
- name: Configure LINBIT public repo
  tags:
    - linstor
    - linstor_registration
  ansible.builtin.include_role:
    name: linbit.common.public_repo
    apply:
      tags:
        - linstor
        - linstor_registration
  when: cluster_init_repo_access == 'public'

- name: Configure LINBIT customer repo
  tags:
    - linstor
    - linstor_registration
  ansible.builtin.include_role:
    name: linbit.common.customer_repo
    apply:
      tags:
        - linstor
        - linstor_registration
  when: cluster_init_repo_access == 'customer'

- name: Install LINSTOR satellite
  tags:
    - linstor
    - linstor_installation
  ansible.builtin.include_role:
    name: linbit.linstor.satellite_install
    apply:
      tags:
        - linstor
        - linstor_installation
  when: inventory_hostname in groups['linstor_satellites']

- name: Install LINSTOR controller
  tags:
    - linstor
    - linstor_installation
  ansible.builtin.include_role:
    name: linbit.linstor.controller_install
    apply:
      tags:
        - linstor
        - linstor_installation
  when: inventory_hostname in groups['linstor_controllers']

- name: Configure LINSTOR SSL/TLS
  tags:
    - linstor
    - linstor_ssl
  ansible.builtin.include_role:
    name: linbit.linstor.ssl_init
    apply:
      tags:
        - linstor
        - linstor_ssl
  vars:
    ssl_init_https_mtls: "{{ cluster_init_ssl_mtls }}"
  when: cluster_init_ssl | bool

- name: Register LINSTOR cluster membership
  tags:
    - linstor
    - linstor_cluster_membership
  ansible.builtin.include_role:
    name: linbit.linstor.cluster_membership
    apply:
      tags:
        - linstor
        - linstor_cluster_membership

- name: Install LINSTOR Gateway
  tags:
    - linstor
    - linstor_installation
    - linstor_gateway
  ansible.builtin.include_role:
    name: linbit.linstor.gateway_install
    apply:
      tags:
        - linstor
        - linstor_installation
        - linstor_gateway
  when: cluster_init_linstor_gateway | bool

- name: Create LINSTOR storage pools
  tags:
    - linstor
    - linstor_storage_pool
  ansible.builtin.include_role:
    name: linbit.linstor.storage_pool
    apply:
      tags:
        - linstor
        - linstor_storage_pool
  when: cluster_init_deploy_storage | bool

# Requires a configured storage pool
- name: Convert LINSTOR database to HA
  tags:
    - linstor
    - linstor_ha_database
  ansible.builtin.include_role:
    name: linbit.linstor.ha_database
    apply:
      tags:
        - linstor
        - linstor_ha_database
  when:
    - cluster_init_deploy_storage | bool
    - cluster_init_ha_database | bool
