# SPDX-License-Identifier: MIT
---
# vars file for linstor_gateway_satellite
linstor_gateway_portblock_ra_dest: '/lib/ocf/resource.d/heartbeat/portblock'

linstor_gateway_ra_packages:
  - resource-agents
