# SPDX-License-Identifier: MIT
---
# tasks file for linstor_gateway_install
- name: Load OS-specific variables for LINSTOR Gateway
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | int }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Gather service facts
  ansible.builtin.service_facts:

# Assume LINSTOR satellite components exist, install if needed
- name: Install LINSTOR satellite components
  ansible.builtin.include_role:
    name: linbit.drbd_reactor.reactor_install
  when: "'linstor-satellite.service' not in ansible_facts.services"

# Assume DRBD Reactor components exist, install if needed
- name: Install DRBD Reactor
  ansible.builtin.include_role:
    name: linbit.drbd_reactor.reactor_install
  when: "'drbd-reactor.service' not in ansible_facts.services"

# Needed if updating new packages
- name: Check for portblock resource agent
  ansible.builtin.stat:
    path: "{{ linstor_gateway_portblock_ra_dest }}"
  register: portblock_ra_check

- name: Fix portblock resource agent - remove immutable flag
  ansible.builtin.file:
    path: "{{ linstor_gateway_portblock_ra_dest }}"
    attributes: '-i'
  when:
    - linstor_gateway_portblock_fix | bool
    - portblock_ra_check.stat.exists

- name: Install LINSTOR Gateway supplemental packages
  ansible.builtin.package:
    name: "{{ linstor_gateway_supplemental_packages + linstor_gateway_ra_packages }}"
    state: present
  ignore_errors: true # for now, clear up packaging assumptions later
  notify: disable_and_stop_nfs

- name: Install SCST
  ansible.builtin.include_role:
    name: linbit.linstor.scst_install
  when:
    - scst is defined
    - scst | bool
    - inventory_hostname in groups['linstor_satellites']

- name: Check if firewalld is running
  ansible.builtin.shell: systemctl status firewalld
  register: linstor_gateway_firewalld
  failed_when: (linstor_gateway_firewalld.rc not in [0, 3, 4])
  changed_when: false
  when: ansible_os_family | lower in ['redhat', 'suse']

- name: Open firewall ports for LINSTOR Gateway (all services)
  ansible.posix.firewalld:
    service: "{{ item.name }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ linstor_gateway_firewalld_services }}"
  when:
    - ansible_os_family | lower in ['redhat', 'suse']
    - linstor_gateway_firewalld.rc is defined
    - linstor_gateway_firewalld.rc == 0

- name: Patch linstor_satellite.toml for DRBD Reactor
  ansible.builtin.blockinfile:
    path: /etc/linstor/linstor_satellite.toml
    marker: "# {mark} ANSIBLE MANAGED FILE"
    block: "{{ lookup('template', 'linstor_satellite.j2') }}"
    create: true
    mode: '644'
    state: present
  notify: Restart linstor-satellite.service

# Only overrite when the RA already exists (resource-agents installed)
- name: Fix portblock resource agent - overwrite and set immutable flag
  ansible.builtin.get_url:
    url: "{{ linstor_gateway_portblock_ra_url }}"
    dest: "{{ linstor_gateway_portblock_ra_dest }}"
    mode: '755'
    attributes: '+i'
  when:
    - linstor_gateway_portblock_fix | bool
    - portblock_ra_check.stat.exists

- name: Flush handlers for current role
  ansible.builtin.meta: flush_handlers
