# SPDX-License-Identifier: MIT
---
# defaults file for controller_install
controller_port: 3370

controller_install_package_state: present

controller_install_gui: true

controller_install_firewall_rules: true

controller_install_firewall_ports:
  - { port: '3370-3371', proto: tcp }

controller_install_force_reconfigure: false
