# SPDX-License-Identifier: MIT
---
# defaults file for linstor_controller
node_type: "{{ 'Combined' if 'linstor_satellites' in group_names else 'Controller' }}"

controller_port: 3370

controller_install_package_state: latest

controller_install_firewall_rules: true

controller_install_firewall_ports:
  - { port: '3370', proto: tcp }
