# SPDX-License-Identifier: MIT
---
# OCF resource agent base path (SUSE uses /usr/lib, others use /lib)
_ra_base: >-
  {{ '/usr/lib/ocf/resource.d/heartbeat'
     if ansible_facts['os_family'] | lower == 'suse'
     else '/lib/ocf/resource.d/heartbeat' }}

_pve_check: >-  # noqa: var-naming[no-role-prefix]
  {{ 'pve' in ansible_facts['kernel'] or
     'proxmox-ve' in (ansible_facts['packages'] | default({})) }}

_ha_gw_mkfs_opts: >- # noqa: var-naming[no-role-prefix]
  {%- if ha_gateway_fstype == 'ext4' -%}
    -b {{ ha_gateway_filesystem_blocksize }}
  {%- elif ha_gateway_fstype == 'xfs' -%}
    -b size={{ ha_gateway_filesystem_blocksize }}
  {%- endif -%}
