# SPDX-License-Identifier: MIT
---
# defaults file for linstor_client
linstor_controller_addresses:
  "{{ groups['linstor_controllers'] | map('extract', hostvars, 'replication_ip') | list | flatten }}"
