# SPDX-License-Identifier: MIT
---
- name: Open firewall ports for LINSTOR controller
  ansible.builtin.include_tasks: open-firewall.yml
  when: controller_install_firewall_rules | bool

- name: Build list of running controller nodes
  ansible.builtin.set_fact:
    _running_controllers: >-
      {{ _running_controllers | default([]) + [item] }}
  when: hostvars[item].ansible_facts.services['linstor-controller.service'].state | default('') == 'running'
  loop: "{{ groups['linstor_controllers'] }}"
  run_once: true  # noqa: run-once[task]

- name: Set active controller count
  ansible.builtin.set_fact:
    _active_count: "{{ _running_controllers | default([]) | length }}"
  run_once: true  # noqa: run-once[task]

- name: Restart LINSTOR controller service when already running and updated
  ansible.builtin.service:
    name: linstor-controller.service
    state: restarted
  when:
    - inventory_hostname in (_running_controllers | default([]))
    - _active_count | int == 1

# Fixes Debian auto-start after initial installation
- name: Stop LINSTOR controller instances when multiple controllers are active
  ansible.builtin.systemd:
    name: linstor-controller.service
    state: stopped
    enabled: false
  when:
    - _active_count | int > 1
    - inventory_hostname not in groups['linstor_controllers'][0]

# Start LINSTOR controller (non-HA operation)
# Also starts LINSTOR controller for initial HA installations (RHEL)
- name: Enable and start LINSTOR controller service (non-HA)
  ansible.builtin.systemd:
    name: linstor-controller.service
    state: started
    enabled: true
  when:
    - ((groups['linstor_controllers'] | length == 1) or
      (_active_count | int == 0))
    - inventory_hostname in groups['linstor_controllers'][0]

- name: Reload service facts
  ansible.builtin.service_facts:

- name: Wait for LINSTOR controller service to respond
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ controller_port }}"
    delay: 1
    timeout: 20
  when:
    - ansible_facts.services['linstor-controller.service'] is defined
    - ansible_facts.services['linstor-controller.service'].state == 'running'
