# SPDX-License-Identifier: MIT
---
- name: Check existing zypper locks
  ansible.builtin.command:
    cmd: zypper locks
  register: _controller_install_zypper_locks
  changed_when: false

- name: Lock LINSTOR controller package versions (Zypper)
  ansible.builtin.command:
    cmd: "zypper addlock {{ item }}"
  loop:
    - linstor-controller
    - linstor-common
  changed_when: true
  when: item not in _controller_install_zypper_locks.stdout
