# SPDX-License-Identifier: MIT
---
# tasks file for linstor_controller
- name: Check for LINSTOR controller updates
  ansible.builtin.package:
    name:
      - linstor-controller
      - linstor-gui
    state: "{{ controller_install_package_state }}"
  register: _controller_install_packages

- name: Configure LINSTOR controller
  ansible.builtin.include_tasks: configure-controller.yml
  when: _controller_install_packages is changed  # noqa: no-handler
