# SPDX-License-Identifier: MIT
---
- name: Remove version locks for LINSTOR controller packages (Zypper)
  ansible.builtin.command:
    cmd: "zypper removelock {{ item }}"
  loop:
    - linstor-controller
    - linstor-common
  changed_when: false
  failed_when: false
