---
- name: LINSTOR cluster membership
  hosts: linstor_controllers,linstor_satellites
  any_errors_fatal: true
  become: true
  tags:
    - linstor
    - linstor_cluster_membership
  tasks:
    - ansible.builtin.import_role:
        name: linbit.linstor.cluster_membership
