# SPDX-License-Identifier: MIT
---
- name: LINSTOR HA database conversion
  hosts: linstor_cluster
  any_errors_fatal: true
  become: true
  tasks:
    - name: Convert LINSTOR database to HA
      vars:
        ha_database_pool: "{{ linstor_sp | default('', true) }}"
      ansible.builtin.import_role:
        name: linbit.linstor.ha_database
