# SPDX-License-Identifier: MIT
---
- name: LINSTOR HA database conversion
  hosts: linstor_cluster
  any_errors_fatal: true
  become: true
  tasks:
    - name: Convert LINSTOR database to HA
      ansible.builtin.import_role:
        name: linbit.linstor.ha_database
