# SPDX-License-Identifier: MIT
---
- name: Install LINSTOR Gateway
  hosts: linstor_controllers,linstor_satellites
  any_errors_fatal: true
  become: true
  roles:
    - role: linbit.linstor.linstor_gateway_install
      tags: linstor_gateway
