- name: LINSTOR Gateway Health Check (check-health)
  hosts: linstor_satellites[0]
  become: true
  tasks:
    - name: Print check-health (Linux-IO Target)
      when: (scst is not defined) or not (scst | bool)
      block:
        - name: Save check-health output (Linux-IO Target)
          ansible.builtin.shell: |
            linstor-gateway check-health --iscsi-backends=lio-t
          register: gateway_health_liot
          changed_when: false
          failed_when: false

        - name: Print check-health (Linux-IO Target)
          ansible.builtin.debug:
            msg: "{{ gateway_health_liot.stdout_lines }}"

    - name: Print check-health (SCST)
      when:
        - scst is defined
        - scst | bool
      block:
        - name: Save check-health output (SCST)
          ansible.builtin.shell: |
            linstor-gateway check-health --iscsi-backends=scst
          register: gateway_health_scst
          changed_when: false
          failed_when: false

        - name: Print check-health (SCST)
          ansible.builtin.debug:
            msg: "{{ gateway_health_scst.stdout_lines }}"
