# SPDX-License-Identifier: MIT
---
# handlers file for linstor_satellite
# Should handle "OS updates" use case, restart on package updates only
- name: Enable and start LINSTOR satellite service
  ansible.builtin.systemd:
    name: linstor-satellite.service
    daemon_reload: true
    state: restarted
    enabled: true
  listen: sat_package_update

- name: Wait for LINSTOR satellite service
  ansible.builtin.wait_for:
    host: localhost
    port: 3366
    delay: 5
    timeout: 20
  listen: sat_package_update
